// src/components/icons/index.js (ĐÃ SỬA LỖI TRIỆT ĐỂ)
import {
    LayoutDashboard,
    ShoppingCart,
    Armchair,
    Users,
    Coffee,
    ClipboardList,
    Archive,
    Truck,
    Contact,
    Calculator,
    BarChart3,
    UserCog,
    ChevronDown,
    LogOut,
    UserCircle,
    Map,
    Printer,
    Trash2,
    CreditCard,
    Landmark,
    DollarSign,
    Ticket,
    Search,
    Notebook,
    Image,
    X
} from 'lucide-vue-next'

export {
    LayoutDashboard,
    ShoppingCart,
    Armchair,
    Users,
    Coffee,
    ClipboardList,
    Archive,
    Truck,
    Contact,
    Calculator,
    BarChart3,
    UserCog,
    ChevronDown,
    LogOut,
    UserCircle,
    Map,
    Printer,
    Trash2,
    CreditCard,
    Landmark,
    DollarSign,
    Ticket,
    Search,
    Notebook,
    Image,
    X
}